### PR TITLE
Replace `condp` with `case` on `.ordinal`

### PR DESCRIPTION
**Pull request by nilern**
Should be a bit faster (seems like 3%).

### CODE REVIEW

**Comment by borkdude** [comment]
I wonder why `*warn-on-reflection*` is set to `false` in project.clj as I wondered if this introduced any reflections (which aren't good for performance and also break GraalVM native-image compilation).

**Comment by nilern** [comment]
I had set `*warn-on-reflection*` to `true` and this does not introduce any reflections (not even at macroexpansion time, which might not even matter).

**Comment by borkdude** [comment]
@nilern Thanks for checking :)

Have you considered just writing a `case` + `(.getName (class ...))` and dispatching on strings? Imo that would make the code more understandable/hacky with perhaps the same per boost.

**Comment by nilern** [comment]
> Have you considered just writing a case + (.getName (class ...)) and dispatching on strings? Imo that would make the code more understandable/less hacky with perhaps the same perf boost.

That sounds *more* hacky to me and surely it is fastest to dispatch on ints.

**Comment by borkdude** [comment]
@nilern Fair point. I had trouble parsing what was going on in your macro, but I expanded it using some test examples locally. Clever.

**Comment by nilern** [comment]
I wish we could just switch on enums directly, like Java. But I was determined to find a way.

**Comment by dakrone** [comment]
Interestingly, this is slightly slower for benchmarks for me with the merging of #174 (and merging master in to use the latest Jackson dependencies). Is it slower for you with these changes as well?

**Comment by dakrone** [comment]
Sounds good, I'll close this for now, we can always re-open in the future if needed!

**Pull request closed without merging**
