### PR TITLE
Update Jackson to latest version

### PR DESCRIPTION
**Pull request by ikitommi**
Update Jackson to latest version

### CODE REVIEW

**Comment by rborer** [comment]
Looks like 2.12.0 was released a couple of weeks ago: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12 . Any possibility to bump to this version & then have a new release of cheshire?

**Comment by borkdude** [comment]
@dakrone This PR is superseded by https://github.com/dakrone/cheshire/pull/172. 

Is there any hesitation to bump Jackson? Why so?

**Comment by borkdude** [comment]
@dakrone If this project is no longer maintained, clj-commons will probably be the place to move this project to if you are open to it.

**Comment by dakrone** [comment]
There is no hesitation, I simply missed this and I've been sick recently. I've pushed a commit that updates to the latest Jackson release.

**Comment by borkdude** [comment]
@dakrone Sorry to hear, hope you are better. Sorry for my impatience :).

**Pull request closed without merging**
