### PR TITLE
Add optional parameter `path-predicate` to check what should be kept in parsed object

### PR DESCRIPTION
**Pull request by DeLaGuardo**

### CODE REVIEW

**Comment by DeLaGuardo** [comment]
Any feedback on that pull request?

**Comment by TwiceII** [comment]
So, @DeLaGuardo, was your PR accepted or what?

**Comment by DeLaGuardo** [comment]
@TwiceII no, it is still open

**Comment by TwiceII** [comment]
I'm getting `Cannot parse #object[com.fasterxml.jackson.core.JsonToken 0x699c2ec8 "FIELD_NAME"]`
when trying to `parsed-seq-strict` nested array of objects like
```
{
  "foo": {"bar": [{"id": 4},
                  {"id": 5}, 
                  {"id": 6}]}
}
```

**Comment by dakrone** [comment]
I apologize for the late feedback. I'm considering whether the additional complexity is worth it in this case. I think the way I would prefer to proceed is to factor predicate parsing into a separate function, so that the regular parsing can stay as simple and fast as possible. Thoughts about that?

**Comment by DeLaGuardo** [comment]
@dakrone sounds reasonable for me. Also my solution is not perfect and might produce strange exceptions as @TwiceII found. So I think it would be better to close that PR) I will come back with another implementation soon.

**Pull request closed without merging**
