### PR TITLE
Replace oraclejdk8 with openjdk8

### PR DESCRIPTION
**Pull request by rymndhng**
TravisCI's Xenial environment no longer provides this environment.

### CODE REVIEW

**Comment by rymndhng** [comment]
Hm, this doens't seem to solve the issue of `openjdk7`. There are two options for us to restore useful CI output. 

1. Set the `dist` to `trusty` for backwards compatibility. This should hypothetically allow us to continue building the existing `jdks`.

2. Remove `openjdk7` from the build. The thinking here is that JDK7 is already end of life, and isn't a platform we need to prioritize testing. 

I would prefer option 2 to keep the project up to date, however I can understand that there may be some consumers of this library who may be stuck on Java 7 and would be benefitted from having these tests pass.

**Comment by rymndhng** [comment]
See #147 for the alternative approach of pinning to `trusty`.

**Comment by dakrone** [comment]
I think dropping jdk7 is fine, it's EOL anyway.

**Comment by rymndhng** [comment]
> I think dropping jdk7 is fine, it's EOL anyway.

Awesome :) This PR should be good to go now!

**Pull request merged**
