### PR TITLE
Add data reader #json tag which generates JSON string

### PR DESCRIPTION
**Pull request by mrroman**
I found it quite helpful with writing tests (don't have to explicitly write json/generate-string in each case) and I think it is quite cool feature.

### CODE REVIEW

**Comment by borkdude** [comment]
If a library would approach such a feature, it's probably better to use a fully qualified keyword for this, to avoid conflicts with other JSON library. Having said this, I don't think this feature has to live inside a library this all and it might be better to leave this choice up to the end user.

**Comment by mrroman** [comment]
Ok, I'll change it to full qualified keyword, but can you elaborate more, why this feature shouldn't be implement inside the library.

**Comment by borkdude** [comment]
I'll leave it up to @dakrone to decide. I don't have a strong opinion on this, as long as there are no conflicts with other libs.

**Comment by dakrone** [comment]
Merged, thanks!

**Pull request merged**
