### PR TITLE
Add parse-stream-strict

### PR DESCRIPTION
**Pull request by nilern**

### CODE REVIEW

**Comment by nilern** [comment]
Travis seems to have trouble installing JDK so my code is not to blame for the failing checks!

**Comment by dakrone** [comment]
@nilern thanks for this! I pushed a fix for Travis to master. Do you think you'd be able to add a sanity test for this new method also? (just that it works, nothing fancy)

**Comment by nilern** [comment]
Of course tests are needed! I just duplicated the `parse-stream` tests for `parse-stream-strict`, that should suffice?

**Comment by dakrone** [comment]
Merged this, thanks @nilern!

**Pull request merged**
