### PR TITLE
Update to jackson 2.10.0

### PR DESCRIPTION
**Pull request by willcohen**

### CODE REVIEW

**Comment by dakrone** [comment]
Merged, thanks!

**Comment by avichalp** [comment]
Thank you for the PR 🙂 

Is there a release planned in the near future?

**Comment by glenjamin** [comment]
Are there any plans to release this soon? We're keen to get off the 2.9 series and avoid having our security tools keep flagging gadgets.

**Comment by dakrone** [comment]
Sure, I can do a release today.

**Comment by dakrone** [comment]
@glenjamin @avichalp I've released 5.10.0, sorry for the delay!

**Comment by glenjamin** [comment]
Awesome, thank you!

**Pull request merged**
